services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tubes2-backend
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tubes2-frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-5173}:80"
    restart: unless-stopped
